### ISSUE TITLE
Error inflating class com.ernestoyaquello.dragdropswiperecyclerview.DragDropSwipeRecyclerView

### ISSUE THREAD

**Issue by JonathanImperato** [ernestoyaquello/DragDropSwipeRecyclerview#14]
Error:  Binary XML file line #19: Binary XML file line #19: Error inflating class com.ernestoyaquello.dragdropswiperecyclerview.DragDropSwipeRecyclerView
This is my layout file:

<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:animateLayoutChanges="true"
    android:background="@drawable/app_background"
    android:paddingTop="?actionBarSize">

    <FrameLayout
        android:layout_width="0dp"
        android:layout_height="0dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent">

        <com.ernestoyaquello.dragdropswiperecyclerview.DragDropSwipeRecyclerView
            android:id="@+id/favsRecyclerView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:visibility="visible"
            app:item_layout="@layout/song_item" />

    </FrameLayout>

    <TextView
        android:id="@+id/no_fav_text"
        style="@style/TrackText"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:animateLayoutChanges="true"
        android:gravity="center"
        android:padding="24dp"
        android:text="@string/no_fav_message"
        android:textAlignment="center"
        android:visibility="invisible"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        tools:visibility="visible" />

</androidx.constraintlayout.widget.ConstraintLayout>

What is wrong? I am using AndroidX

By the way the library is really well made. Thanks a lot for your effort!

**Comment by ernestoyaquello** [comment]
Unfortunately, I don't think I can do much with the information you have provided. Could you provide some of the following?

- A sample project with the issue so I can reproduce it locally (this would be ideal).
- The code of all the files involved in implementing and setting up the list.
- The full error log of the exception.

Besides, I would recommend you double check that you have followed all the necessary steps to set up the library correctly (i.e., adding the library to your Gradle file, creating and setting the adapter, the layout manager and the orientation; etc).

**Comment by JonathanImperato** [comment]
I've found it was a problem due to Kotlin, you can use the library in java but you need to add Kotlin support that sometimes goes in contrast with some other libraries...that was it. Sorry for the spam

**Comment by ernestoyaquello** [comment]
I will investigate this, maybe I have to add something to make the library usable in Java without hassle. Thanks for the information!

**Comment by ernestoyaquello** [comment]
BTW, @JonathanImperato, could you please tell me what library exactly did you have to add to your project?

**Comment by JonathanImperato** [comment]
Sure, it was the Realm library. Everything was fine except your library when I was not using the kotlin plugin, than, once I understood I had to add the kotlin plugin Realm started crashing. I found the Realm solution here: https://realm.io/docs/java/latest/#kotlin

**Comment by webserveis** [comment]
I same the problem I use Java with AndroidX

I Declare this
`xml
    <com.ernestoyaquello.dragdropswiperecyclerview.DragDropSwipeRecyclerView
        android:id="@+id/list"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:item_layout="@layout/list_item_layout"
        app:layout_behavior="@string/appbar_scrolling_view_behavior" />
`

Error log
`
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.webserveis.testkeyvalue/com.example.webserveis.testkeyvalue.KeyValueActivity}: android.view.InflateException: Binary XML file line #23: Error inflating class com.ernestoyaquello.dragdropswiperecyclerview.DragDropSwipeRecyclerView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2339)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)
        at android.app.ActivityThread.access$800(ActivityThread.java:155)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5343)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
     Caused by: android.view.InflateException: Binary XML file line #23: Error inflating class com.ernestoyaquello.dragdropswiperecyclerview.DragDropSwipeRecyclerView
        at android.view.LayoutInflater.createView(LayoutInflater.java:633)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:470)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:141)
        at com.example.webserveis.testkeyvalue.KeyValueActivity.onCreate(KeyValueActivity.java:22)
        at android.app.Activity.performCreate(Activity.java:6010)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413) 
        at android.app.ActivityThread.access$800(ActivityThread.java:155) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5343) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
        at android.view.LayoutInflater.createView(LayoutInflater.java:607)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:470) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:141) 
        at com.example.webserveis.testkeyvalue.KeyValueActivity.onCreate(KeyValueActivity.java:22) 
        at android.app.Activity.performCreate(Activity.java:6010) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413) 
        at android.app.ActivityThread.access$800(ActivityThread.java:155) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5343) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
        at com.ernestoyaquello.dragdropswiperecyclerview.DragDropSwipeRecyclerView.<init>(DragDropSwipeRecyclerView.kt)
        at com.ernestoyaquello.dragdropswiperecyclerview.DragDropSwipeRecyclerView.<init>(DragDropSwipeRecyclerView.kt:26)
        at com.ernestoyaquello.dragdropswiperecyclerview.DragDropSwipeRecyclerView.<init>(DragDropSwipeRecyclerView.kt)
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:470) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:141) 
        at com.example.webserveis.testkeyvalue.KeyValueActivity.onCreate(KeyValueActivity.java:22) 
        at android.app.Activity.performCreate(Activity.java:6010) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413) 
        at android.app.ActivityThread.access$800(ActivityThread.java:155) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5343) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.jvm.internal.Intrinsics" on path: DexPathList[[zip file "/data/app/com.example.webserveis.testkeyvalue-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.ernestoyaquello.dragdropswiperecyclerview.DragDropSwipeRecyclerView.<init>(DragDropSwipeRecyclerView.kt) 
        at com.ernestoyaquello.dragdropswiperecyclerview.DragDropSwipeRecyclerView.<init>(DragDropSwipeRecyclerView.kt:26) 
        at com.ernestoyaquello.dragdropswiperecyclerview.DragDropSwipeRecyclerView.<init>(DragDropSwipeRecyclerView.kt) 
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:470) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:141) 
        at com.example.webserveis.testkeyvalue.KeyValueActivity.onCreate(KeyValueActivity.java:22) 
        at android.app.Activity.performCreate(Activity.java:6010) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413) 
        at android.app.ActivityThread.access$800(ActivityThread.java:155) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5343) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700) 
    	Suppressed: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)`

**Comment by JonathanImperato** [comment]
I am using android X and java as well and to me the problem has been fixed
with this pull.

Il lun 18 feb 2019, 10:01 Gerard Coll <notifications@github.com> ha scritto:
